services:

  project-server:
    build:
      context: ./server/project-service/
      dockerfile: Dockerfile
    restart: always
    container_name: ${PROJECT_SERVICE_HOST}
    hostname: ${PROJECT_SERVICE_HOST}
    ports:
      - 8080:8080
    environment:
      - PORT=${PORT}
      - MONGO_DB_URI=${MONGO_DB_URI_PROJECT}
      - NATS_URL=nats://nats:4222
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${PORT}
      - TASK_SERVICE_HOST=${TASK_SERVICE_HOST}
      - TASK_SERVICE_PORT=${PORT}
    volumes:
      - ./server/project-service/app.log:/app.log




    depends_on:
      mongo-project:
        condition: service_healthy
      nats:
        condition: service_started

  # NoSQL: MongoDB
  mongo-project:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_project_store:/data/db

  angular-app:
    build:
      context: ./client/ui-trello
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - "4200:4200"
    volumes:
      - ./client/ui-trello:/app
      - /app/node_modules
      - ./api-gateway:/app/api-gateway
    depends_on:
      - project-server
      - user-server
      - task-server
      - notification-server
    environment:
      - CHOKIDAR_USEPOLLING=true
    mem_limit: 2g

  mongo-express-project:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=${PROJECT_HOST} #mongo-project
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME} #root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD} #pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI_PROJECT} #mongodb://root:pass@mongo-project:27017
    depends_on:
      - mongo-project
    ports:
      - "8081:8081"
    volumes:
      - mong_project_express_data:/data/db



  task-server:
    build:
      context: ./server/task-service/
      dockerfile: Dockerfile
    restart: always
    container_name: ${TASK_SERVICE_HOST}
    hostname: ${TASK_SERVICE_HOST}
    ports:
      - 8089:8080
    environment:
#      - PORT=8080
#      - MONGO_DB_URI=mongodb://root:pass@mongo-task:27017
#      - NATS_URL=nats://nats:4222
        - PORT=${PORT}
        - MONGO_DB_URI=${MONGO_DB_URI_TASK}
        - NATS_URL=nats://nats:4222
        - USER_SERVICE_HOST=${USER_SERVICE_HOST}
        - USER_SERVICE_PORT=${PORT}
    volumes:
      - ./server/task-service/app.log:/app.log
    depends_on:
      mongo-task:
        condition: service_healthy
      nats:
        condition: service_started


  mongo-task:
    image: mongo
    restart: always
    ports:
      - "27019:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoTask
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_task_store:/data/db


  mongo-express-task:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-task
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=mongodb://root:pass@mongo-task:27017
    depends_on:
      - mongo-task
    ports:
      - "8088:8081"
    volumes:
      - mongo_task_express_data:/data/db



  user-server:
    build:
      context: ./server/user-service/
      dockerfile: Dockerfile
    restart: always
    container_name: ${USER_SERVICE_HOST}
    hostname: ${USER_SERVICE_HOST}
    env_file:
      - .env
    ports:
      - 8090:8080
    environment:
      - PORT=${PORT}
      - MONGO_DB_URI=${MONGO_DB_URI_USER} #mongodb://root:pass@mongo-user:27017
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - CAPTCHA=${CAPTCHA}
      - REDIS_HOST=${REDIS_HOST}
    depends_on:
      mongo-user:
        condition: service_healthy
    volumes:
      - ./server/user-service/10k-worst-passwords.txt:/app/10k-worst-passwords.txt
      - ./server/user-service/app.log:/app.log


  mongo-user:
    image: mongo
    restart: always
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDb
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_user_store:/data/db

  mongo-express-user:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo-user
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI} #mongodb://root:pass@mongo-user:27017
    depends_on:
      - mongo-user
    ports:
      - "8083:8081"
    volumes:
      - mong_user_express_data:/data/db

  api_gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: on-failure
    ports:
      - "443:443"
    depends_on:
      - user-server
      - project-server
      - angular-app
      - task-server
      - notification-server
    entrypoint: [ "/bin/bash", "-c", "while ! curl -s user-server:8080; do sleep 1; done; nginx -g 'daemon off;'" ]

  redis:
    image: redis:alpine
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  notification-server:
    build:
      context: ./server/notification-service/
      dockerfile: Dockerfile
    restart: always
    container_name: "notification-service"
    hostname: "notification-service"
    ports:
      - "8085:8080"
    environment:
      - PORT=${PORT}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
    depends_on:
      cassandra:
        condition: service_healthy
      nats:
        condition: service_started

  cassandra:
    image: cassandra:4.0
    restart: always
    container_name: "cassandra"
    hostname: "cassandra"
    ports:
      - "9042:9042"
    environment:
      - CASSANDRA_CLUSTER_NAME=MyCassandraCluster
      - CASSANDRA_DC=DC1
      - CASSANDRA_RACK=RAC1
      - CASSANDRA_LISTENER_RPC_ADDRESS=0.0.0.0
    healthcheck:
      test: ["CMD", "cqlsh", "--username", "cassandra", "--password", "cassandra", "--execute", "describe keyspaces"]
      interval: 15s
      retries: 5
      timeout: 15s
    volumes:
      - cassandra_data:/var/lib/cassandra

  nats:
    image: 'nats:latest'
    expose:
      - "4222"
    ports:
      - "4222:4222"


volumes:
  mongo_project_store:
  mongo_user_store:
  mongo_task_store:
  mong_user_express_data:
  mong_project_express_data:
  redis_data:
  cassandra_data:
  mongo_task_express_data:
