services:

  project-server:
    build:
      context: ./server/project-service/
      dockerfile: Dockerfile
    restart: always
    container_name: ${PROJECT_SERVICE_HOST}
    hostname: ${PROJECT_SERVICE_HOST}
    ports:
      - ${PROJECT_SERVER_PORT}
    environment:
      - PORT=${PORT}
      - MONGO_DB_URI=${MONGO_DB_URI_PROJECT}
      - NATS_URL=${NATS_URL}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${PORT}
      - TASK_SERVICE_HOST=${TASK_SERVICE_HOST}
      - TASK_SERVICE_PORT=${PORT}
    env_file: ".env"
    volumes:
      - ./server/project-service/app.log:/app.log
      - ./server/project-service/cert.crt:/app/cert.crt
      - ./server/project-service/privat.key:/app/privat.key
    depends_on:
      mongo-project:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - network

  # NoSQL: MongoDB
  mongo-project:
    image: mongo
    restart: always
    ports:
      - ${MONGO_PROJECT_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
    env_file: ".env"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_project_store:/data/db
    networks:
      - network

  angular-app:
    build:
      context: ./client/ui-trello
      dockerfile: Dockerfile
    container_name: angular-app
    ports:
      - ${ANGULAR_APP_PORT}
    volumes:
      - ./client/ui-trello:/app
      - /app/node_modules
      - ./api-gateway:/app/api-gateway
    depends_on:
      - project-server
      - user-server
      - task-server
      - notification-server
      - workflow-server
    environment:
      - CHOKIDAR_USEPOLLING=true
    env_file: ".env"
    mem_limit: 2g
    networks:
      - network

  mongo-express-project:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=${PROJECT_HOST} 
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${MONGO_INITDB_ROOT_USERNAME} 
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${MONGO_INITDB_ROOT_PASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI_PROJECT}
    env_file: ".env"
    depends_on:
      - mongo-project
    ports:
      - ${MONGO_EXPRESS_PROJECT_PORTS}
    volumes:
      - mong_project_express_data:/data/db
    networks:
      - network



  task-server:
    build:
      context: ./server/task-service/
      dockerfile: Dockerfile
    restart: always
    container_name: ${TASK_SERVICE_HOST}
    hostname: ${TASK_SERVICE_HOST}
    ports:
      - ${TASK_SERVER_PORTS}
    environment:
      - PORT=${PORT}
      - NATS_URL=${NATS_URL}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
      - MONGO_DB_URI=${MONGO_DB_URI_TASK}
      - USER_SERVICE_HOST=${USER_SERVICE_HOST}
      - USER_SERVICE_PORT=${PORT}
    env_file: ".env"
    volumes:
      - ./server/task-service/app.log:/app.log
      - ./server/task-service/cert.crt:/app/cert.crt
      - ./server/task-service/privat.key:/app/privat.key
    depends_on:
      mongo-task:
        condition: service_healthy
      nats:
        condition: service_started
    networks:
      - network

  mongo-task:
    image: mongo
    restart: always
    ports:
      - ${MONGO_TASK_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE_TASK}
    env_file: ".env"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_task_store:/data/db
    networks:
      - network


  mongo-express-task:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${ME_CONFIG_MONGODB_URL}
    env_file: ".env"
    depends_on:
      - mongo-task
    ports:
      - ${MONGO_EXPRESS_TASK_PORT}
    volumes:
      - mongo_task_express_data:/data/db
    networks:
      - network



  user-server:
    build:
      context: ./server/user-service/
      dockerfile: Dockerfile
    restart: always
    container_name: ${USER_SERVICE_HOST}
    hostname: ${USER_SERVICE_HOST}
    env_file: ".env"
    ports:
      - 8090:8080
    environment:
      - PORT=${PORT}
      - MONGO_DB_URI=${MONGO_DB_URI_USER}
      - SMTP_EMAIL=${SMTP_EMAIL}
      - SMTP_PASSWORD=${SMTP_PASSWORD}
      - SMTP_HOST=${SMTP_HOST}
      - SMTP_PORT=${SMTP_PORT}
      - REDIS_PORT=${REDIS_PORT}
      - CAPTCHA=${CAPTCHA}
      - REDIS_HOST=${REDIS_HOST}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
    depends_on:
      mongo-user:
        condition: service_healthy
    volumes:
      - ./server/user-service/10k-worst-passwords.txt:/app/10k-worst-passwords.txt
      - ./server/user-service/cert.crt:/app/cert.crt
      - ./server/user-service/privat.key:/app/privat.key
      - ./server/user-service/app.log:/app.log
    networks:
      - network


  mongo-user:
    image: mongo
    restart: always
    ports:
      - ${MONGO_USER_PORT}
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE_USER}
    env_file: ".env"
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_user_store:/data/db
    networks:
      - network

  mongo-express-user:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=${ME_CONFIG_MONGODB_SERVER_USER}
      - ME_CONFIG_MONGODB_ADMINUSERNAME=${ME_CONFIG_MONGODB_ADMINUSERNAME}
      - ME_CONFIG_MONGODB_ADMINPASSWORD=${ME_CONFIG_MONGODB_ADMINPASSWORD}
      - ME_CONFIG_BASICAUTH_USERNAME=${ME_CONFIG_BASICAUTH_USERNAME}
      - ME_CONFIG_BASICAUTH_PASSWORD=${ME_CONFIG_BASICAUTH_PASSWORD}
      - ME_CONFIG_MONGODB_URL=${MONGO_DB_URI}
    env_file: ".env"
    depends_on:
      - mongo-user
    ports:
      - "8083:8081"
    volumes:
      - mong_user_express_data:/data/db
    networks:
      - network

  api_gateway:
    build:
      context: ./api-gateway/
      dockerfile: Dockerfile
    container_name: api-gateway
    restart: on-failure
    env_file: ".env"
    ports:
      - ${API_GATEWAY_PORTS}
    depends_on:
      - user-server
      - project-server
      - angular-app
      - task-server
      - notification-server
      - workflow-server
    entrypoint: [ "/bin/bash", "-c", "while ! curl -s user-server:8080; do sleep 1; done; nginx -g 'daemon off;'" ]
    networks:
      - network

  redis:
    image: redis:alpine
    restart: always
    env_file: ".env"
    ports:
      - ${REDIS_PORT}:${REDIS_PORT}
    volumes:
      - redis_data:/data
    networks:
      - network

  notification-server:
    build:
      context: ./server/notification-service/
      dockerfile: Dockerfile
    restart: always
    container_name: "notification-service"
    env_file: ".env"
    hostname: "notification-service"
    ports:
      - ${NOTIFICATION_SERVER_PORT}
    environment:
      - PORT=${PORT}
      - CASSANDRA_HOST=${CASSANDRA_HOST}
      - CASSANDRA_PORT=${CASSANDRA_PORT}
      - CASSANDRA_KEYSPACE=${CASSANDRA_KEYSPACE}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
    depends_on:
      cassandra:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ./server/notification-service/cert.crt:/app/cert.crt
      - ./server/notification-service/privat.key:/app/privat.key
    networks:
      - network

  cassandra:
    image: cassandra:4.0
    restart: always
    container_name: "cassandra"
    hostname: "cassandra"
    env_file: ".env"
    ports:
      - ${CASSANDRA_PORT}:${CASSANDRA_PORT}
    environment:
      - CASSANDRA_CLUSTER_NAME=${CASSANDRA_CLUSTER_NAME}
      - CASSANDRA_DC=${CASSANDRA_DC}
      - CASSANDRA_RACK=${CASSANDRA_RACK}
      - CASSANDRA_LISTENER_RPC_ADDRESS=${CASSANDRA_LISTENER_RPC_ADDRESS}
    healthcheck:
      test: ["CMD", "cqlsh", "--username", "cassandra", "--password", "cassandra", "--execute", "describe keyspaces"]
      interval: 15s
      retries: 5
      timeout: 15s
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - network

  nats:
    image: 'nats:latest'
    env_file: ".env"
    expose:
      - ${NATS_PORT}
    ports:
      - ${NATS_PORT}:${NATS_PORT}
    networks:
      - network

  tracing:
    image: jaegertracing/all-in-one:latest
    env_file: ".env"
    container_name: jaeger
    ports:
      - "${UDP_PORT}:${UDP_PORT}/udp"
      - "${JAEGER_UI_PORT}:${JAEGER_UI_PORT}"
      - "${JAEGER_THRIFT_PORT}:${JAEGER_THRIFT_PORT}"
      - "${OTLP}:${OTLP}"
    environment:
      - COLLECTOR_ZIPKIN_HTTP_PORT=${COLLECTOR_ZIPKIN_HTTP_PORT}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
    networks:
      - network

  workflow-server:
    build:
      context: ./server/workflow-service/
      dockerfile: Dockerfile
    restart: always
    container_name: "workflow-service"
    env_file: ".env"
    hostname: "workflow-service"
    ports:
      - ${WORKFLOW_SERVICE_PORT}
    environment:
      - PORT=${PORT}
      - NATS_URL=${NATS_URL}
      - NEO4J_DB=${NEO4J_DB}
      - NEO4J_USERNAME=${NEO4J_USERNAME}
      - NEO4J_PASS=${NEO4J_PASS}
      - JAEGER_ADDRESS=${JAEGER_ADDRESS}
    depends_on:
      neo4j:
        condition: service_healthy
      nats:
        condition: service_started
    volumes:
      - ./server/workflow-service/cert.crt:/app/cert.crt
      - ./server/workflow-service/privat.key:/app/privat.key
      - ./server/project-service/app.log:/app.log
    networks:
      - network

  neo4j:
    image: neo4j
    restart: always
    ports:
      - "7687:7687"
      - "7474:7474"
      - "7473:7473"
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "echo RETURN 1 | cypher-shell -a bolt://neo4j:7687 -u neo4j -p strongerpassword || exit 1",
        ]
      interval: 5s
      timeout: 5s
      retries: 10
    environment:
      - NEO4J_AUTH=neo4j/strongerpassword
    volumes:
      - neo4j_data:/data
    networks:
      - network

volumes:
  mongo_project_store:
  mongo_user_store:
  mongo_task_store:
  mong_user_express_data:
  mong_project_express_data:
  redis_data:
  cassandra_data:
  mongo_task_express_data:
  neo4j_data:

networks:
  network:
    driver: bridge
