version: "3.1"

services:

  user-server:
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    container_name: "user-server"
    hostname: "user-server"
    ports:
      - 8080:8080
    environment:
      - PORT=8080

      - MONGO_DB_URI=mongodb://root:pass@mongo:27017

    depends_on:
      mongo:
        condition: service_healthy

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: pass
      MONGO_INITDB_DATABASE: mongoDemo
    healthcheck:
      test: echo 'db.runCommand("ping").ok'
      interval: 10s
      timeout: 10s
      retries: 10
    volumes:
      - mongo_store:/data/db

  mongo-express:
    image: mongo-express
    restart: always
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ADMINUSERNAME=root
      - ME_CONFIG_MONGODB_ADMINPASSWORD=pass
      - ME_CONFIG_BASICAUTH_USERNAME=admin
      - ME_CONFIG_BASICAUTH_PASSWORD=admin
    depends_on:
      - mongo
    ports:
      - "8081:8081"
    volumes:
      - mong_express_data:/data/db

volumes:
  mongo_store:
  mong_express_data:
